### ISSUE TITLE
Decide on Language.

### ISSUE THREAD

**Issue by Husterknupp** [Husterknupp/jubilant-todo-tribble#1]
Java?
Kotlin?

**Comment by Bantolomeus** [comment]
*closed eyes* 
*points on Kotlin*

**Comment by Husterknupp** [comment]
Then let's do it!

**Kotlin**

**Comment by Husterknupp** [comment]
Orient towards https://git.spreadomat.net/sprd/customer-service-cockpit
- kotlin
- spring boot
- maven
