### ISSUE TITLE
make linux build stable

### ISSUE THREAD

**Issue by Bantolomeus** [Husterknupp/jubilant-todo-tribble#21]
- [ ] make linux build great again

**Comment by Husterknupp** [comment]
configuring the travis jvm to java 8 should fix the problem

https://blog.travis-ci.com/2013-11-26-test-your-java-libraries-on-java-8/

the issue title has a typo btw

**Comment by Husterknupp** [comment]
@Bantolomeus what's left to do on this one?

**Comment by Husterknupp** [comment]
u nailed it buddy!
