### ISSUE TITLE
introduce develop branch

### ISSUE THREAD

**Issue by Bantolomeus** [Husterknupp/jubilant-todo-tribble#22]
- [x] create develop branch

**Comment by Bantolomeus** [comment]
from now on push your features into develop and release milestones into master
@Husterknupp feel free to state your opinion, if you have any other suggestions

**Comment by Husterknupp** [comment]
@Bantolomeus until we have an MVP released there is no much value in having a master branch different from develop, what do you think?

But after the mvp was released I totally agree with you. Unless we wanna try out the more continuous approach of other guys that release every commit that passes the CI stages ;-)

**Comment by Bantolomeus** [comment]
true, after MVP is released, we will use the develop branch. See it now as a test branch for travis configuration =)
