### ISSUE TITLE
create a web interface

### ISSUE THREAD

**Issue by Bantolomeus** [Husterknupp/jubilant-todo-tribble#24]
- [ ] make buttons (wow)
- [ ] make everything else
- [ ] make make more subtasks

**Comment by Husterknupp** [comment]
let's please draw a sketch of the UI and at least 1 use case

**Comment by Husterknupp** [comment]
how much is this one related to #10

**Comment by Bantolomeus** [comment]
As we elaborated, this is not needed, thats why I close it
