### ISSUE TITLE
Connect to gitlab

### ISSUE THREAD

**Issue by Husterknupp** [Husterknupp/jubilant-todo-tribble#3]
Read codebase of arbitrary repo and walk path

- [x] arbitrary gitlab repo: 
- [x] find a way to get all files and folders in a repo
- [x] find gitlab endpoint url for a file
- [x] auth needed for read access?
- [x] printout single line to see that the reading works

**Comment by Bantolomeus** [comment]
still on it

**Comment by Bantolomeus** [comment]
project id: 1801

**Comment by Bantolomeus** [comment]
curl --header "PRIVATE-TOKEN: {privateToken}" "https://{urlToYourGitlab}/api/v4/projects/1801/repository/files/pom%2Exml/raw?ref=master"

**Comment by Bantolomeus** [comment]
to get the repository root:
curl --header "PRIVATE-TOKEN: {privateToken}" "https://{yourRepoName}/api/v4/projects/1801/repository/tree"

**Comment by Bantolomeus** [comment]
TODO: create task to navigate through all folders of a project to get all files

**Comment by Bantolomeus** [comment]
Authentication is needed. Can be done with private token. Later we need to use sudo: https://docs.gitlab.com/ee/api/#sudo
