### ISSUE TITLE
Find and store todos with context

### ISSUE THREAD

**Issue by Husterknupp** [Husterknupp/jubilant-todo-tribble#5]
- [x] find not too excessive way to iterate trough file tree
- [x] printout number of files included in the repo
- [x] find all todos

store:
- [x] each todo line number
- [x] literal code line of todo
- [x] 7 lines of context (if given) up and 7 lines down
- [x] email + user name of committer (for now project creator see #3)

**Comment by Bantolomeus** [comment]
```
val continueSearching = true
val result = searchHelp(rootTreeUrl)
var filesList: List = result.files
var treeList: List = result.trees
var treeUrl;
while (result.hasTrees() ) {
  treeUrl = treeList.next()
  result = searchHelp(treeUrl)
  treeList.remove(treeUrl)
  filesList.add(result.files)
  treeList.add(result.trees)
}

function searchHelp(url: String) {
  open(url)
  return {trees: [], files: []}
}
```

**Comment by Husterknupp** [comment]
navigate through folders using `path` query param: 
`/api/v4/projects/1801/repository/tree?path=src/main&private_token=PRIVATE_TOKEN`

**Comment by Husterknupp** [comment]
can find files. For directory urls I need to handle the url a little smarter..
