### ISSUE TITLE
Connect to Jira

### ISSUE THREAD

**Issue by Husterknupp** [Husterknupp/jubilant-todo-tribble#7]
Programmatically create an issue

- [x] find jira endpoint url/method for creating new issues
- [x] how to do auth?
- [x] don't put Jira url or any credentials in code base
- [x] use dev project (get id)
- [x] use issue engineering issue type (get id)
- [x] define assignee
- [x] define issue title
- [x] define issue description
- [x] implement the connection
- [x] log that new issue has been created

**Comment by Bantolomeus** [comment]
Jira version: JIRA v7.2.6

**Comment by Bantolomeus** [comment]
To authenticate you simply add a parameter in the url, like in the curl command above.

**Comment by Bantolomeus** [comment]
@Husterknupp can you pls define where we should log, if a new issue is created?

**Comment by Husterknupp** [comment]
@Bantolomeus yes, you're absolutely right. The idea was to add transparency on what our app is doing. Everytime it finds a new todo and adds a Jira issue for that todo, an interested person should be able to find information about it. Either in logs or as a REST endpoint or whatever. I found the logging option the easiest for now.

**Comment by Bantolomeus** [comment]
a example curl command to create a issue (documented [https://developer.atlassian.com/jiradev/jira-apis/jira-rest-apis?_ga=1.183138022.1717742076.1475583437:here](url))
`curl -u admin:admin -X POST --data @data.txt -H "Content-Type: application/json" http://localhost:8080/jira/rest/api/2/issue/`

data.txt:
`{
    "fields": {
       "project":
       {
          "id": "10000"
       },
       "summary": "No REST for the Wicked.",
       "description": "Creating of an issue using ids for projects and issue types using the REST API",
       "issuetype": {
          "id": "3"
       }
   }
}`

**Comment by Bantolomeus** [comment]
To get the meta datas of our jira you can use this curl command: 
`curl -D- -u username:password -X GET -H "Content-Type: application/json" https://jira.whatEver/api/2/issue/createmeta`

**Comment by Bantolomeus** [comment]
for assignee you can use the name shortage from gitlab (between two and four letters)

**Comment by Bantolomeus** [comment]
for now create a standard component and always use this standard component.

**Comment by Bantolomeus** [comment]
see #10 for later component setting handling

**Comment by Bantolomeus** [comment]
summary in data.txt is the issue title

**Comment by Bantolomeus** [comment]
here is a link of possible settings: https://community.atlassian.com/t5/Answers-Developer-Questions/How-to-add-component-while-creating-an-issue-via-JIRA-REST-API/qaq-p/493660

**Comment by Bantolomeus** [comment]
curl command to create a new issue:
`curl -u username:password -X POST --data @data.txt -H "Content-Type: application/json" https://jiraAdress/rest/api/2/issue/`

data.txt:
`{
    "fields": {
        "project": {
            "id": "projectId"
        },
        "summary": "title",
        "description": "description",
        "issuetype": {
            "id": "issueTypeId"
        },
        "assignee": {
            "name": "username"
        },
        "components": [
            {
                "id": "componentId"
            }
        ]
    }
}`

**Comment by Husterknupp** [comment]
for how to add json object to your http request, look here: http://khttp.readthedocs.io/en/latest/user/quickstart.html#more-complicated-post-requests

**Comment by Husterknupp** [comment]
we need 1. Authorization and 2. content-type header
```
val authHeader = String(Base64.getEncoder().encode("USERNAME:PW".toByteArray()));
        // addHeader("Authorization", "Basic " + auth);
        // setHeader("content-type", "application/json");
```

**Comment by Bantolomeus** [comment]
for further usage the createJiraIssue method needs configurable summary and description

**Comment by Husterknupp** [comment]
@Bantolomeus Code is not compiling. see my code comment.

**Comment by Husterknupp** [comment]
https://github.com/Husterknupp/jubilant-todo-tribble/commit/afee3fb12fb8178332f3559ea05b58b5fdde10fc#commitcomment-21935226

**Comment by Bantolomeus** [comment]
I get this error: 
(default) on project jubilant-todo-tribble: The plugin pl.project13.maven:git-commit-id-plugin:2.2.1 requires Maven version [3.1.1,) -> [Help 1]

@Husterknupp Did you added this? Can you solve this?
I have a lot more dependency errors

**Comment by Husterknupp** [comment]
I didn't add the git-commit-id plugin lately. It's in the repo since the beginning.

Did you checkout the latest commit and tried `mvn clean compile -U` ?

Am 27.04.2017 um 18:38 schrieb Christian Bantel <notifications@github.com<mailto:notifications@github.com>>:


I get this error:
(default) on project jubilant-todo-tribble: The plugin pl.project13.maven:git-commit-id-plugin:2.2.1 requires Maven version [3.1.1,) -> [Help 1]

@Husterknupp<https://github.com/Husterknupp> Did you added this? Can you solve this?
I have a lot more dependency errors

**Comment by Bantolomeus** [comment]
I still have the dependency problems. Thats why I can not run mvn test. I pushed the credentials class with all needed methods. @Husterknupp please test if the application runs if you pull and fill out the Return values in Credentials.kt with the correct values

**Comment by Bantolomeus** [comment]
I had to delete and recreate the Credentials class to be able to commit it.

**Comment by Husterknupp** [comment]
@Bantolomeus sorry for this gitignore hassle. Thank you for the now compiling code. Let me double check if I have dependency problems. 

In the meanwhile maybe this can be useful for you https://deutsch.lingolia.com/en/vocabulary/easily-confused-words/das-vs-dass

**Comment by Husterknupp** [comment]
`mvn -U clean package` outputs `BUILD SUCCESS` for me. What are your dependency problems?

**Comment by Husterknupp** [comment]
Implementation wise, can you please rework the issue title and the issue description to be method params? Makes sense to actually put information about a todo into the issue, right?

**Comment by Bantolomeus** [comment]
Done and of course it makes sense.

**Comment by Husterknupp** [comment]
method params found
