### ISSUE TITLE
Remember todos that are referenced in an issue already

### ISSUE THREAD

**Issue by Husterknupp** [Husterknupp/jubilant-todo-tribble#8]
- [x] how to detect changes
 - [x] where to remember the found todos?
 - [x] implementation

**Comment by Husterknupp** [comment]
options: 
1) hash over todo line and remember that hash - if hash found earlier, no action required (pro: | con: todos with same text would create same duplette todo)
2) hash over todo line + context - if hash found earlier, no action required (pro: more unlikely to find duplicate | con: change in the context would create a new todo)
3) hash over todo line + file name (pro: unlikely to find same todo line in a single file twice | con: cannot have same todo in the same file multiple times) <-- prefered option

**Comment by Husterknupp** [comment]
Let's remember the found todos in a `todos-so-far` file in the root directory

**Comment by Husterknupp** [comment]
@Bantolomeus 

my idea is as follows:
- TodoScanner calls TodoHistory.saveIfNew(todo) on every scheduled scan
- new TodoHistory class saves new ones and remembers for which todos there was a jira issue created
- your Jira class calls TodoHistory.getUnnoticedTodos() and creates new Jira issues for each of the returned todos
- on every successful issue creation, the Jira class calls TodoHistory.markAsNoticed(todo, jiraTicketId) and tells the TodoHistory that it did its job

what u think?

**Comment by Bantolomeus** [comment]
The saved Jira issues contains the response from the issue creation? That would be good, it contains  information we could use for further functionality. Lets investigate which data of the response are useful if not all.
If my Jira class shall call TodoHistory.getUnnoticedTodos(), then it has to be a scheduled task. Wouldn't it be better if the TodoScanner calls a Jira class method, which calls TodoHistory.getUnnoticedTodos()? Or is that what you mean? 
As mentioned before, wouldn't it be great to save more then just the JiraTicketId? Something like TodoHistory.markAsNoticed(todo, JiraIssueCreationResponse).

Else I find it good.

**Comment by Husterknupp** [comment]
@Bantolomeus I am very fine saving all data from the issue creation that we might need further on. Let's only save now what we need now and extend the data model once we need more data. I guess for now some information on wether an issue was created for a given todo together with the issue link if it given might be good. Because Jira shows you all the data that you wanna know. What details besides would you want to show?

I also thought about the Scanner calling Jira. But it feels strange. The Scanner should be responsible for scanning and not for Issue creation. Also imagine you want to add a GitHubHandler. With your suggestion you would need to extend the TodoScanner as well which sounds not intended. Yah, all the JiraHandler should have a scheduled method that checks regularely the TodoHistory on unnoticed todos.

**Comment by Bantolomeus** [comment]
You are right. We do not want a "god scanner" ^^
I guess, the link would be enough for now.

**Comment by Husterknupp** [comment]
I see 4 states that a todo can have, currently

1. todo created, according issue not created
2. todo created, acc. issue created
3. todo removed, acc. issue not updated
4. todo removed, acc. issue updated

I will for the beginning only implement 1. and 2. 
cases 3./4. (removed todo detection) should be covered later

**Comment by Bantolomeus** [comment]
5. todo updated, acc. issue not updated
6 todo updated, acc. issue updated

**Comment by Husterknupp** [comment]
@Bantolomeus I don't know what you mean by 5. and 6. What does an update mean? Can you elaborate a bit pls?

Change of the todo line string? How could we detect that?

**Comment by Bantolomeus** [comment]
I am sorry that it was not clear. In my point of view I did the same as you.
Yes I mean a change of the todo String. 
How we detect it? The same way we detect new Todos. We scan the files and if there is a Todo, we look up our Todo history for this project and if we find like 80% matching words (lets talk about that) of an already detected Todo and it is in the same line (for now to make it not too complicated) as the existing Todo from this file, than we say it is the same Todo which has to be updated.
