### ISSUE TITLE
Schedule repeated repo scanning

### ISSUE THREAD

**Issue by Husterknupp** [Husterknupp/jubilant-todo-tribble#9]
- [x] create empty method for later implementation
 - [x] add implementation to the method
 - [x] double check todo counting

**Comment by Husterknupp** [comment]
implementation is done ✅ 

Will run a test against one of my repos and see if new commits are being noticed and stored

**Comment by Husterknupp** [comment]
finding todos works pretty well. Tested for a one-file project and a 100+ file project (jsoup)

Todos are not stored though. Missed that part of linking the scanner with the repository

**Comment by Husterknupp** [comment]
cool, saving works as well as noticing. `INFO [2017-05-06 23:31:08] d.h.t.TodoScanner - found 48 todos (0 are new)`

But the count looks strange. Should be more than 48 todos

**Comment by Bantolomeus** [comment]
Nice progress

**Comment by Husterknupp** [comment]
numbers doublechecked. They look good. I miscounted in my earlier comment. Mixed found files count with found todo count
